#services:
#  pgvector:
#    image: 'pgvector/pgvector:pg16'
#    environment:
#      - 'POSTGRES_DB=ics'
#      - 'POSTGRES_PASSWORD=postgres'
#      - 'POSTGRES_USER=postgres'
#    labels:
#      - "org.springframework.boot.service-connection=postgres"
#    ports:
#      - '5432'
version: '3'  # Add version directive

services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      POSTGRES_DB: ics
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'  # Map host port 5432 to container port 5432
